if(NOT DEFINED PIPELINE_MODE)
  message(FATAL_ERROR "PIPELINE_MODE is required")
endif()
if(NOT DEFINED PIPELINE_PROFILE)
  message(FATAL_ERROR "PIPELINE_PROFILE is required")
endif()
if(NOT DEFINED PIPELINE_BUILD_DIR)
  message(FATAL_ERROR "PIPELINE_BUILD_DIR is required")
endif()
get_filename_component(source_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(build_root "${PIPELINE_BUILD_DIR}" ABSOLUTE BASE_DIR "${source_root}")

set(report_root "${source_root}/.pipeline-state/reports")
if(PIPELINE_MODE STREQUAL "check-fast")
  file(MAKE_DIRECTORY "${report_root}/check-fast")
  file(WRITE "${report_root}/check-fast/configure.json" "{\"outcome\":\"passed\",\"assertions\":1,\"configured\":true}\n")
  return()
endif()

if(WIN32)
  set(platform "win")
  set(binary "${build_root}/win/Release/px4xplane/64/win.xpl")
elseif(APPLE)
  set(platform "mac")
  set(binary "${build_root}/mac/Release/px4xplane/64/mac.xpl")
elseif(UNIX)
  set(platform "lin")
  set(binary "${build_root}/lin/Release/px4xplane/64/lin.xpl")
else()
  message(FATAL_ERROR "Unsupported plugin build host")
endif()

get_filename_component(plugin_root "${binary}" DIRECTORY)
get_filename_component(plugin_root "${plugin_root}" DIRECTORY)
set(config_file "${plugin_root}/64/config.ini")
set(readme_file "${plugin_root}/README.md")
set(airframes_dir "${plugin_root}/px4_airframes")
foreach(required IN ITEMS "${binary}" "${config_file}" "${readme_file}")
  if(NOT EXISTS "${required}" OR IS_DIRECTORY "${required}")
    message(FATAL_ERROR "Missing required plugin output: ${required}")
  endif()
endforeach()
file(SIZE "${binary}" binary_bytes)
if(binary_bytes LESS 1)
  message(FATAL_ERROR "Plugin binary is empty")
endif()
file(SHA256 "${binary}" binary_sha256)
file(GLOB airframe_files LIST_DIRECTORIES false "${airframes_dir}/*")
list(LENGTH airframe_files airframe_count)
if(airframe_count LESS 1)
  message(FATAL_ERROR "No PX4 airframe files were copied into the plugin output")
endif()

set(artifact_json "null")
if(PIPELINE_MODE STREQUAL "package")
  set(artifact "${source_root}/.pipeline-state/packages/px4xplane-ci-${platform}.tar.gz")
  file(MAKE_DIRECTORY "${source_root}/.pipeline-state/packages")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar czf "${artifact}" --format=gnutar px4xplane
    WORKING_DIRECTORY "${build_root}/${platform}/Release"
    RESULT_VARIABLE archive_result
    ERROR_VARIABLE archive_error
  )
  if(NOT archive_result EQUAL 0 OR NOT EXISTS "${artifact}")
    message(FATAL_ERROR "Failed to retain plugin artifact: ${archive_error}")
  endif()
  file(SIZE "${artifact}" artifact_bytes)
  file(SHA256 "${artifact}" artifact_sha256)
  set(artifact_json "{\"path\":\".pipeline-state/packages/px4xplane-ci-${platform}.tar.gz\",\"bytes\":${artifact_bytes},\"sha256\":\"${artifact_sha256}\"}")
endif()

if(PIPELINE_MODE STREQUAL "check")
  set(suite "check")
elseif(PIPELINE_MODE STREQUAL "package")
  set(suite "package")
else()
  message(FATAL_ERROR "Unsupported PIPELINE_MODE: ${PIPELINE_MODE}")
endif()
file(MAKE_DIRECTORY "${report_root}/${suite}")
file(WRITE "${report_root}/${suite}/plugin-build.json"
  "{\"outcome\":\"passed\",\"assertions\":5,\"platform\":\"${platform}\",\"binary\":\"${binary}\",\"binaryBytes\":${binary_bytes},\"binarySha256\":\"${binary_sha256}\",\"configPresent\":true,\"readmePresent\":true,\"airframeFiles\":${airframe_count},\"artifact\":${artifact_json}}\n")
